leejarvis/slop

- lib/slop/parser.rb
- test/parser_test.rb
The double dash is a valid (special) option for Slop, so like the rest of the options successfully processed, should be removed.
> Remove "--" from the unprocessed arguments

- lib/slop/error.rb
- lib/slop/option.rb
- lib/slop/parser.rb
- test/error_test.rb
Allows MissingArgument and UnknownOption error classes to carry information regarding "what option/flag"
**MissingArgument** gets a second parameter in its initialize function, which takes an array of the flags matching the option which misses an argument
**MissingArgument** also gets a *string[] getFlags()* which returns these flags
**UnknownOption** get a second parameter in its initialize function, which takes the option that was unknown.
**UnknownOption** also gets a **_string[]_** *getUnknownOption()* which return the unknown option
The throwing of **UnknownOption** and **MissingArgument** has been rewritten to match the new parameter list of the initialize of these classes.
And tests have been written for the new functionality.
btw: Type in the commit message, it says "Implement …
> Implement string[] MissingArgument.flags and string UnknownOption.flag

- README.md
- lib/slop/option.rb
- lib/slop/result.rb
- test/option_test.rb
- test/result_test.rb
At the moment, the behaviour is a bit odd for options with multiple word names (e.g. `--long-option-name`) where you end up with strange behaviour on `Slop::Result` where you end up with odd symbol keys, which look like `:"long-option-name"` rather than `:long_option_name` as you'd naturally expected.
I've made various fixes to make this work as you'd expect, as well as supporting features like the `?` accessor methods.
Keen to hear your thoughts on this. Seems like a nicer and more idiomatic Ruby behaviour. Tested it somewhat but you may well have a view on testing it more or less.
> Better handling of option names with multiple words

- lib/slop/types.rb
- test/types_test.rb
The --no- prefix was setting the final option correctly, but always passing true as the block argument regardless - see tests.
> Fix bug where true is passed to BoolOption block regardless of --no- prefix

- README.md
- lib/slop/types.rb
- test/types_test.rb
I'd like to allow my users to supply an argument multiple times on the command line, which slop supports, but the arguments can contain commas. Instead of setting the delimiter to something silly like `thisisnotadelimiter` or `_________` or `\0` to prevent unintended behavior, allow disabling the delimiter by setting it to `nil`. 
UPDATE: Well, I just realized that I can simply set the array option limit to one (1) to get the behavior I'm looking for. I'll leave this PR open in case you think it's still useful to add. Thank you...
> Allow disabling the delimiter for array arguments

- lib/slop/options.rb
- test/options_test.rb
The usage message displays the script name as the entire path of when the script was called. If the script is called from a directory other than the one it is in, it will display that entire path. 
See here for an example showing several parent directories in the usage:
This lets the user specify a banner string via the config hash to allow them to override the text shown in the banner.
> Can specify a custom banner string in Options via config

- lib/slop/parser.rb
- lib/slop/types.rb
- test/parser_test.rb
This allows negative values as arguments to numeric options and strings
starting with - for any other type.
Fixes #170
Fixes #179
> Support arguments to options with leading -

- lib/slop/options.rb
`sort_by` does not ensure the original order is kept for sequences with the same sort value.
This fixes it by keeping the original index as a secondary sort param.
> inside tail sort, retain original sort order

- .travis.yml
This PR introduces 2 new Rubies to the matrix: latest stable Ruby and JRuby.
It changes `gem update bundler` to `gem install bundler`. (Why? "gem update bundler" is a noop is there's no `bundler` gem installed, which was the case in `jruby-head`, which led to a build failure because the default shell script that runs "bundle install ..." failed with a "can not find `bundler`".)
> Travis: use 2.4.0, latest stable JRuby

- lib/slop/parser.rb
- test/error_test.rb
There's an oversight in the `partition` method (which treats all arguments following `--` as ignored arguments) where it does not work correctly if `partition_idx` is zero (i.e. `--` is the first element in the string array). This patch fixes this erroneous behavior and adds a small spec for it.
> Fix bug preventing '--' being passed as the first argument.

- README.md
- lib/slop/error.rb
- lib/slop/option.rb
- lib/slop/parser.rb
- test/error_test.rb
I've been needing this in one of my own projects and I saw that someone previously requested it in #203, so I went ahead and implemented it :smile: 
Let me know if you'd like me to update the README and/or Gem version in this PR as well.
Thanks for the awesome library!
Fixes #203
> Support for required options

- README.md
Follows up on #218 -- I only half updated the example there, and left out the new option in the `opts` and `opts.to_hash` demonstrations.  Sorry!
> README: Fix example to include required option

- .travis.yml
This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/12/07/jruby-9-1-15-0.html
> Travis: use JRuby 9.1.16.0 in the CI matrix

- lib/slop/error.rb
- lib/slop/result.rb
- test/result_test.rb
Sometimes I want to raise an error when a given key is not present (for avoid typos for example) so this change implements Slop::Result#fetch allows the following:
```ruby
opts = Slop.parse do |o|
o.string '-name'
end
ARGV #=> --name giovanni
opts[:name]          # giovanni
opts.fetch(:name) # giovanni
opts.fetch(:namr)      # raises KeyError: key not found: 'namr'
opts.fetch(:last_name) # raises KeyError: key not found: 'last_name'
```
`Slop::Result#fetch` returns the value associated to a given key as `Slop::Result#[]`  and `Slop::Result#get` but raises `KeyError` if it does not exist.
> Add Slop::Result#fetch

- CHANGELOG.md
This PR makes the CHANGELOG.md document easier to navigate when using the GitHub site: **issues and pull requests are now links**.
> CHANGELOG.md: Linkify, format heading

- lib/slop/parser.rb
- test/parser_test.rb
If flag value starts with "-", unknown option error is raised.
The current flag value check is "orig_arg == opt.value.to_s". There
are some objects such as Regexp and Time that input value and its #to_s
aren't same.
> Fix a bug that flag value is processed as flag

- lib/slop/types.rb
- test/types_test.rb
Right now, if I have define
````
opts.integer '--modify-capacity',
'Modify the desired ECS cluster size (defaults to zero, which means no change)',
default: 0
````
and call it with `command --modify-capacity +50`, slop doesn't recognise it as `50`, but instead uses `0`, which is default value. Simple change into regular expression should solve this issue (unless it breaks some other functionality in slop).
> Support '+' as prefix for integer

- lib/slop/parser.rb
Silences the warning about this variable not being used.
```
...slop/parser.rb:55: warning: assigned but unused variable - orig_arg
```
Looks like this was added [here](https://github.com/leejarvis/slop/commit/7f6aef195716989d8fb7e66b1ca52e348551b67a) and the usage was removed [here](https://github.com/leejarvis/slop/commit/c026ee99247c33130addc01d1399e71b14879f38#diff-20549db7eca9a25c33580b3f08335fb4).
> remove unused variable

- .travis.yml
- lib/slop/options.rb
- test/option_test.rb
- test/options_test.rb
- test/types_test.rb
Fixing tests to work with ruby 2.7.0 (also tested with ruby 2.6.3 and 2.5.1)
With current master, we stumble into following error messages on ruby 2.7.0:
```
[~/github/slop]% rake test                                                                   [master]
/Users/jylitalo/github/slop/test/types_test.rb:42: warning: ambiguous first argument; put parentheses or a space even after `-' operator
Run options: --seed 59555
/Users/jylitalo/github/slop/lib/slop/options.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/jylitalo/github/slop/lib/slop/parser.rb:13: warning: The called method `initialize' is defined here
/Users/jylitalo/github/slop/test/options_test.rb:124: warning: Using the last argument as keyword parameters …
```
> Tests on Ruby 2.7.0: avoid warnings; add 2.7.0 to CI

- lib/slop/types.rb
- test/types_test.rb
- parse the float with a prepended + sign
- parse scientific notations
- remove the todo comment
> FloatOption: Add support for scientific notation and + sign

- lib/slop.rb
At least one more warning escaped #248.
> Fix one more keyword argument warning

- .travis.yml
This PR updates the CI matrix to use latest JRuby, **9.2.14.0**.
[JRuby 9.2.14.0 release blog post](https://www.jruby.org/2020/12/08/jruby-9-2-14-0.html)
> CI: Use jruby-9.2.14.0

- README.md
- lib/slop/types.rb
- test/types_test.rb
I also noticed that `StringOption` didn't have any tests, so I added some (very, very simple) tests for it.
> Add symbols to option types

- lib/slop/options.rb
rake test before change results in about 5 errors.
rake test after change had no errors.
> changed str << to str +=

- .github/workflows/ci.yml
This PR adds Ruby 3.0 and 3.1 to the CI matrix.
> Add Ruby 3.0 and 3.1 to the CI matrix

- lib/slop/parser.rb
- test/parser_test.rb
Previously, `--message="key=value"` produced `{:message=>"key"}` because the flag regex stopped looking for more characters at the first equals sign.
> Handle strings containing =

- README.md
- lib/slop/types.rb
- test/types_test.rb
When a boolean option is explicitly set to `false`, e.g.:
```bash
--option=false
```
it enters slop as the string value `'false'`. This commit updates the
`BoolOption` option handler to interpret `'false'` and various other falsey
values (`false`, `'false'`, `'no'`, `'off'`, `'0'`) as logically false.
> Fix explicitly false booleans

- README.md
- lib/slop/error.rb
- lib/slop/option.rb
- lib/slop/options.rb
- lib/slop/types.rb
- test/error_test.rb
- test/types_test.rb
Hi there!
I was replacing OptionParser on a project with Slop, but noticed it would use a predefined default value instead of raising an error if a provided value could not be applied to a given option. (Fixes #262)
This PR adds a new option, `validate_types` to both `Option` and `Options`, allowing types to be checked while maintaining compatibility with Slop's current behaviour, so no breaking changes are introduced.
> Add support to optional type validation

- slop.gemspec
RubyGems.org no longer uses test_files for anything.
> Drop unused test_files directive
